email_verify.settings:
  type: mapping
  label: Settings
  mapping:
    email_verify_active:
      type: boolean
    email_verify_user_registration:
      type: boolean
    email_verify_user_profile:
      type: boolean
    email_verify_site_contact:
      type: boolean
    email_verify_personal_contact:
      type: boolean
    email_verify_host_name:
      type: string
    email_verify_timeout:
      type: integer
    email_verify_checkdnsrr:
      type: boolean
    email_verify_gethostbyname:
      type: boolean
    email_verify_add_dot:
      type: boolean
